plugins { id 'fabric-loom' }
base { archivesName = 'core-affinity-fabric' }
dependencies {
    minecraft 'com.mojang:minecraft:1.21.1'
    mappings 'net.fabricmc:yarn:1.21.1+build.3:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.16.14'
    implementation project(':common')
    include project(':common')
    include 'net.java.dev.jna:jna:5.14.0'
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
}
jar {
    from(rootProject.file('LICENSE'))
    from(rootProject.file('THIRD-PARTY-NOTICES.md'))
}
