plugins { id 'fabric-loom' version '1.17.21' apply false }
allprojects {
    group = 'dev.bigcore'
    version = '1.0.0+mc1.21.1'
    repositories { mavenCentral() }
}
subprojects {
    apply plugin: 'java-library'
    java { toolchain { languageVersion = JavaLanguageVersion.of(21) }; withSourcesJar() }
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.release = 21 }
    tasks.withType(Test).configureEach { useJUnitPlatform() }
}
